global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:80']
    metrics_path: /metrics

  - job_name: 'scraping-service'
    static_configs:
      - targets: ['scraping-service:80']
    metrics_path: /metrics

  - job_name: 'search-service'
    static_configs:
      - targets: ['search-service:80']
    metrics_path: /metrics

  - job_name: 'reporting-service'
    static_configs:
      - targets: ['reporting-service:80']
    metrics_path: /metrics

  - job_name: 'deduplication-service'
    static_configs:
      - targets: ['deduplication-service:80']
    metrics_path: /metrics

  - job_name: 'alert-service'
    static_configs:
      - targets: ['alert-service:80']
    metrics_path: /metrics
